// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Person.proto

package Person

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Person struct {
	Firstname            string   `protobuf:"bytes,1,opt,name=Firstname,proto3" json:"Firstname,omitempty"`
	Middlename           []string `protobuf:"bytes,2,rep,name=Middlename,proto3" json:"Middlename,omitempty"`
	Lastname             string   `protobuf:"bytes,3,opt,name=Lastname,proto3" json:"Lastname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_841ab6396175eaf3, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *Person) GetMiddlename() []string {
	if m != nil {
		return m.Middlename
	}
	return nil
}

func (m *Person) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func init() {
	proto.RegisterType((*Person)(nil), "Person")
}

func init() { proto.RegisterFile("Person.proto", fileDescriptor_841ab6396175eaf3) }

var fileDescriptor_841ab6396175eaf3 = []byte{
	// 103 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x09, 0x48, 0x2d, 0x2a,
	0xce, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x4a, 0xe2, 0x62, 0x83, 0xf0, 0x85, 0x64,
	0xb8, 0x38, 0xdd, 0x32, 0x8b, 0x8a, 0x4b, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35,
	0x38, 0x83, 0x10, 0x02, 0x42, 0x72, 0x5c, 0x5c, 0xbe, 0x99, 0x29, 0x29, 0x39, 0xa9, 0x60, 0x69,
	0x26, 0x05, 0x66, 0x0d, 0xce, 0x20, 0x24, 0x11, 0x21, 0x29, 0x2e, 0x0e, 0x9f, 0x44, 0xa8, 0x66,
	0x66, 0xb0, 0x66, 0x38, 0x3f, 0x89, 0x0d, 0x6c, 0x95, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xb8,
	0xb7, 0xe7, 0x79, 0x7a, 0x00, 0x00, 0x00,
}
